### PR TITLE
Update wpautoload.php

### PR DESCRIPTION
**Pull request by jegbagus**
use absolute path instead of relative path to fix composer.json not found

### CODE REVIEW

**Comment by wppunk** [comment]
Could you describe the steps to reproduce?

**Comment by jegbagus** [comment]
composer.json 

`{
  "name": "my-blocks/My-blocks",
  "require": {
    "wppunk/wpautoload": "^0.2.0"
  },
  "extra": {
    "wp-autoload": {
      "My\\Blocks\\": "includes/"
    }
  }
}
`

it will cause issue composer.json not found

https://p69.f3.n0.cdn.getcloudapp.com/items/rRuorZ4x/Screen%20Shot%202020-11-16%20at%2009.12.43.png?source=viewer&v=dc882fe5d2f31eaa7178d6cb02847fcc

**Comment by wppunk** [comment]
@jegbagus Do you the `vendor/autoload.php` file?

**Comment by jegbagus** [comment]
yes i already include `vendor/autoload.php` on plugin file.

**Pull request closed without merging**
